### ISSUE TITLE
Bug in anchor handling?

### ISSUE THREAD

**Issue by jcfj** [chyh1990/yaml-rust#166]
I encountered the following yaml document [in the wild](https://github.com/weaveworks/eksctl/issues/1104):
```yaml
nodeGroups:
  - <<: &node-shared
      privateNetworking: true
      ssh:
        allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
  - name: ng-2
    <<: *node-shared
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
```
Parsing and printing it with:
```rust
    println!("{:#?}", yaml_rust::YamlLoader::load_from_str(example).unwrap()[0]);
```
on yaml-rust v0.4.4 yields something odd:
```
Hash(
    {
        String(
            "nodeGroups",
        ): Array(
            [
                Hash(
                    {
                        String(
                            "<<",
                        ): Hash(
                            {
                                String(
                                    "privateNetworking",
                                ): Boolean(
                                    true,
                                ),
                                String(
…
```
Notice the `String("<<")`?

Is that a bug in the parser, or is that document simply not valid YAML 1.2?
