### ISSUE TITLE
Parsing Types

### ISSUE THREAD

**Issue by hoodie** [chyh1990/yaml-rust#7]
Hi, I've tried out this crate and noticed that it does not support certain types of data.
I parsed this (extended) [example from wikipedia](https://en.wikipedia.org/wiki/YAML#Casting_data_types):
```yaml
---
a: 123                    # an integer
b: "123"                  # a string, disambiguated by quotes
c: 123.0                  # a float
d: !!float 123            # also a float via explicit data type prefixed by (!!)
e: !!str 123              # a string, disambiguated by explicit type
f: !!str Yes              # a string via explicit type
g: Yes                    # a boolean True
g1: !!bool Yes            # a boolean True
g2: !!bool True           # a boolean True
g3: True                  # a boolean True
h: Yes we have No bananas # a string, "Yes" and "No" disambiguated by context.
```
Where the values `g*` ought to be parsed as boolean. Instead they are parsed as `String` or even `BadValue`. The standard is a bit vague on the issue. Yaml1.2 mentions only `true` and `false` while the 1.1 also allows 
```regex
 y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF
```
I know you stated this is a yaml1.2 lib, but for compatibility reasons, would you be willing to add this to the crate?
