### ISSUE TITLE
"<<:" merge operator is not a key

### ISSUE THREAD

**Issue by fzzr-** [chyh1990/yaml-rust#82]
```yaml
fn test_yaml()
{
        let s =
"
%YAML 1.2
---

defaults: &super
  a:      valueA
  b:      valueB

sub:
  <<: *super
  b:      valueB_new
  c:      valueC
";
    // load:
    let docs = YamlLoader::load_from_str(s).unwrap();
    let doc = &docs[0];
    println!("doc: {:?}", doc);

    // dump & print:
    let mut out_str = String::new();
    {
        let mut emitter = YamlEmitter::new(&mut out_str);
        emitter.dump(doc).unwrap();
    }
    println!("rerender:\n{}", out_str);
}
```

- - -

Current **unexpected** output:

```
rerender:
---
defaults:
  a: valueA
  b: valueB
sub:
  "<<":
    a: valueA
    b: valueB
  b: valueB_new
  c: valueC
```

There `"<<":` is a key.
